// <auto-generated />
using System;
using CretanMusicians.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CretanMusicians.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231018183834_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CretanMusicians.Domain.Entities.Musician", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_musicians");

                    b.ToTable("musicians", (string)null);
                });

            modelBuilder.Entity("CretanMusicians.Domain.Entities.Musician", b =>
                {
                    b.OwnsMany("CretanMusicians.Domain.Entities.Instrument", "Instruments", b1 =>
                        {
                            b1.Property<Guid>("MusicianId")
                                .HasColumnType("uuid")
                                .HasColumnName("musician_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("MusicianId", "Id")
                                .HasName("pk_instruments");

                            b1.ToTable("instruments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MusicianId")
                                .HasConstraintName("fk_instruments_musicians_musician_id");
                        });

                    b.Navigation("Instruments");
                });
#pragma warning restore 612, 618
        }
    }
}
